spring:
  main:
    web-application-type: none
  datasource:
    mysql:
      jdbc-url: jdbc:mariadb://localhost:3306/zzangho
      driver-class-name: org.mariadb.jdbc.Driver
      username: root
      password: 1q2w3e4r5t

elasticsearch:
  host: localhost
  port: 9200
bulk:
  dir: /Users/zzangho/data/bulk/news
  file-name: news_bulk.json
#  batch:
#    job:
#      names: ${job.name:NONE}